;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua-cut-region
	cua-delete-region
	cua-insert-char-rectangle
	cua-set-rectangle-mark
	))

(setq mc/cmds-to-run-once
      '(
	cua-resize-rectangle-right
	enlarge-window-horizontally
	))
